package com.globalfun.adventuretime.free;

/* JADX INFO: loaded from: classes.dex */
public abstract class Resources {
    public static int[] COLORS_ARM;
    public static int[] DUNGEON_TILE;
    public static int[] DUNGEON_TRANSFORM;
    public static int FRAME_HIT_BICLOPS;
    public static int FRAME_HIT_HAMMER;
    public static int FRAME_HIT_PENGUIN;
    public static int FRAME_HIT_SWORD;
    public static int GFX_ARM_OY;
    public static int[] GFX_ARM_STRIPES;
    public static int GFX_BG_FINN_OX;
    public static int GFX_BG_FINN_OY;
    public static int GFX_BORDER;
    public static int[][] GFX_BOSS_DIRS;
    public static int[][] GFX_BOSS_HEIGHT;
    public static int[][] GFX_BOSS_OX;
    public static int[][] GFX_BOSS_OY;
    public static boolean[] GFX_BOSS_SHADOW;
    public static int[] GFX_BOSS_SHADOW_OY;
    public static int[][] GFX_BOSS_WIDTH;
    public static int GFX_BRACKET_HEIGHT;
    public static int GFX_BRACKET_OX;
    public static int GFX_BRACKET_OY;
    public static int GFX_BRACKET_WIDTH;
    public static int[] GFX_FX_HEIGHT;
    public static int[] GFX_FX_OX;
    public static int[] GFX_FX_OY;
    public static int[] GFX_FX_WIDTH;
    public static int GFX_GRAVITY_DROP;
    public static int GFX_GRAVITY_FALL;
    public static int GFX_GRAVITY_FOUND;
    public static int GFX_HAND_OX;
    public static int GFX_HAND_OY;
    public static int GFX_JUMP_ARROW;
    public static int[] GFX_JUMP_BICLOPS;
    public static int[] GFX_JUMP_BOUNCE;
    public static int GFX_JUMP_BUBBLE;
    public static int[] GFX_JUMP_BURGER;
    public static int GFX_JUMP_DROP;
    public static int GFX_JUMP_EYE_FIRE;
    public static int GFX_JUMP_FALL;
    public static int[] GFX_JUMP_FLOAT;
    public static int GFX_JUMP_FOUND;
    public static int GFX_JUMP_FX;
    public static int GFX_JUMP_MAGIC;
    public static int GFX_JUMP_PICKUP;
    public static int[] GFX_JUMP_ZOMBIE2;
    public static int GFX_LOGO_HEIGHT;
    public static int GFX_LOGO_WIDTH;
    public static int GFX_MAP_DOOR_OX;
    public static int GFX_MAP_DOOR_OY;
    public static int GFX_MAP_DOOR_WIDTH;
    public static int GFX_MAP_GRID_HEIGHT;
    public static int GFX_MAP_GRID_WIDTH;
    public static int GFX_MAP_ICON_HEIGHT;
    public static int GFX_MAP_ICON_WIDTH;
    public static int GFX_MAP_ROOM_HEIGHT;
    public static int GFX_MAP_ROOM_INSET;
    public static int GFX_MAP_ROOM_WIDTH;
    public static int[] GFX_NUM_BOSS_SPRITES;
    public static int GFX_PORTRAIT_HEIGHT;
    public static int GFX_PORTRAIT_OVER;
    public static int GFX_PORTRAIT_WIDTH;
    public static int GFX_PRINCESS_BUBBLE_OY;
    public static int GFX_PRINCESS_HEIGHT;
    public static int GFX_PRINCESS_OX;
    public static int GFX_PRINCESS_OY;
    public static int GFX_PRINCESS_WIDTH;
    public static int GFX_SCROLL_CENTER_HEIGHT;
    public static int GFX_SCROLL_CENTER_WIDTH;
    public static int GFX_SCROLL_END_HEIGHT;
    public static int GFX_SCROLL_END_OVER;
    public static int GFX_SCROLL_END_WIDTH;
    public static int GFX_SCROLL_SIDE_HEIGHT;
    public static int GFX_SCROLL_SIDE_WIDTH;
    public static int[] GFX_SHADOW_OY;
    public static int GFX_SOFTKEY_HEIGHT;
    public static int GFX_SOFTKEY_WIDTH;
    public static int GFX_STATUS_DIGITS_OY;
    public static int GFX_STATUS_DIGIT_HEIGHT;
    public static int GFX_STATUS_DIGIT_WIDTH;
    public static int[] GFX_STATUS_DIGIT_WIDTHS;
    public static int GFX_STATUS_ICON_HEIGHT;
    public static int GFX_STATUS_ICON_SPACING;
    public static int GFX_STATUS_ICON_WIDTH;
    public static int GFX_TITLE_BORDER_HEIGHT;
    public static int GFX_TITLE_BORDER_OX;
    public static int GFX_TITLE_BORDER_OY;
    public static int GFX_TITLE_BORDER_SIZE;
    public static int GFX_TITLE_BORDER_WIDTH;
    public static int GFX_TOUCHPAD_HBORDER;
    public static int GFX_TOUCHPAD_VBORDER;
    public static int GFX_TOUCH_ACTION_HEIGHT;
    public static int GFX_TOUCH_ACTION_WIDTH;
    public static int GFX_TOUCH_CONTROLS_HSPACING;
    public static int GFX_TOUCH_CONTROLS_VSPACING;
    public static int GFX_TOUCH_DIR_HEIGHT;
    public static int[] GFX_TOUCH_DIR_OX;
    public static int[] GFX_TOUCH_DIR_OY;
    public static int GFX_TOUCH_DIR_WIDTH;
    public static int GFX_TOUCH_PAD_HEIGHT;
    public static int GFX_TOUCH_PAD_WIDTH;
    public static int[] GFX_TOUCH_POS_OX;
    public static int[] GFX_TOUCH_POS_OY;
    public static int[] OVERWORLD_TILE;
    public static int[] OVERWORLD_TRANSFORM;
    public static int NUM_SOUNDS = 8;
    public static int SOUND_BGM_THEME = 0;
    public static int[] SOUND_BGM_DUNGEON = {1, 2, 3, 4};
    public static int SOUND_BGM_BOSS = 5;
    public static int SOUND_SFX_BOSS_DEFEAT = 6;
    public static int SOUND_SFX_KILLED = 7;
    public static int GFX_ROOM_SIZE = 48;
    public static int GFX_TILE_SIZE = 25;
    public static int GFX_OBJECT_SIZE = 24;
    public static int GFX_ROOM_BORDER = 12;
    public static int GFX_NUM_TYPES = 20;
    public static int[] GFX_NUM_SPRITES = {10, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2};
    public static int[][] GFX_SPRITE_WIDTH = {new int[]{25, 25, 44, 44, 28, 20, 36, 18, 24, 27}, new int[]{19}, new int[]{28}, new int[]{21}, new int[]{31}, new int[0], new int[0], new int[0], new int[0], new int[]{25}, new int[]{23}, new int[]{26}, new int[]{29, 37}, new int[]{24}, new int[]{27, 41}, new int[]{26}, new int[]{18}, new int[]{28}, new int[]{24}, new int[]{27, 10}};
    public static int[][] GFX_SPRITE_HEIGHT = {new int[]{34, 31, 60, 60, 36, 20, 54, 18, 36, 34}, new int[]{22}, new int[]{28}, new int[]{25}, new int[]{29}, new int[0], new int[0], new int[0], new int[0], new int[]{33}, new int[]{31}, new int[]{23}, new int[]{32, 53}, new int[]{34}, new int[]{35, 64}, new int[]{25}, new int[]{21}, new int[]{28}, new int[]{30}, new int[]{35, 10}};
    public static int[][] GFX_SPRITE_OX = {new int[]{12, 12, 18, 18, 14, 10, 12, 9, 12, 13}, new int[]{9}, new int[]{14}, new int[]{10}, new int[]{15}, new int[0], new int[0], new int[0], new int[0], new int[]{12}, new int[]{11}, new int[]{13}, new int[]{14, 12}, new int[]{12}, new int[]{13, 13}, new int[]{13}, new int[]{9}, new int[]{14}, new int[]{11}, new int[]{13, 5}};
    public static int[][] GFX_SPRITE_OY = {new int[]{25, 19, 36, 36, 27, 10, 32, 9, 28, 24}, new int[]{13}, new int[]{20}, new int[]{17}, new int[]{21}, new int[0], new int[0], new int[0], new int[0], new int[]{28}, new int[]{26}, new int[]{16}, new int[]{25, 36}, new int[]{27}, new int[]{27, 32}, new int[]{18}, new int[]{16}, new int[]{14}, new int[]{16}, new int[]{24, 5}};
    public static int[][] GFX_SPRITE_NUM_DIRS = {new int[]{4, 1, 3, 3, 3, 1, 3, 1, 1, 1}, new int[]{3}, new int[]{1}, new int[]{1}, new int[]{1}, new int[0], new int[0], new int[0], new int[0], new int[]{4}, new int[]{1}, new int[]{2}, new int[]{3, 3}, new int[]{1}, new int[]{3, 3}, new int[]{1}, new int[]{1}, new int[]{1}, new int[]{1}, new int[]{1, 1}};
    public int[] SOUND_BGM_RAW = {R$raw.theme, R$raw.dungeon0, R$raw.dungeon1, R$raw.dungeon2, R$raw.dungeon3, R$raw.bossfight, R$raw.bossdefeat, R$raw.dead};
    public boolean USES_PALETTES = true;
    public boolean HAS_DETAILED_ABYSS = true;
    public boolean HAS_ROOM_SHADOWS = true;
    public boolean HAS_ACTOR_SHADOWS = true;
    public boolean HAS_MENU_BG = true;
    public boolean HAS_SPLIT_BG = false;
    public boolean HAS_LOGO_ANIM = true;
    public boolean HAS_SCROLL = true;
    public boolean HAS_ILLUSTRATIONS = true;
    public boolean HAS_CURSOR_ARM = true;
    public String[] FILENAMES_RES = {"/res-finn.bin", "/res-chars.bin", "/res-common.bin"};
    public String FILENAME_FONT = "/font-pp_9x11.cf";
    public String FILENAME_FONT_W = "/font-pp-white_9x11.cf";
    public String FILENAME_SOUND = "/s.bin";
    public int LOGO_ID_TITLE = 2;

    static {
        int[] iArr = new int[42];
        iArr[0] = 7;
        iArr[2] = 7;
        iArr[3] = 7;
        iArr[4] = 7;
        iArr[9] = 4;
        iArr[10] = 4;
        iArr[11] = 4;
        iArr[12] = 4;
        iArr[15] = 4;
        iArr[16] = 4;
        iArr[18] = 9;
        iArr[39] = 4;
        iArr[40] = 4;
        iArr[41] = 4;
        GFX_SHADOW_OY = iArr;
        FRAME_HIT_SWORD = 2;
        FRAME_HIT_HAMMER = 2;
        FRAME_HIT_PENGUIN = 1;
        FRAME_HIT_BICLOPS = 2;
        GFX_PRINCESS_WIDTH = 27;
        GFX_PRINCESS_HEIGHT = 58;
        GFX_PRINCESS_OX = 13;
        GFX_PRINCESS_OY = 50;
        GFX_PRINCESS_BUBBLE_OY = 20;
        GFX_FX_WIDTH = new int[]{37, 33, 20, 22, 66, 19, 23, 16, 58};
        GFX_FX_HEIGHT = new int[]{37, 38, 23, 21, 56, 18, 20, 16, 64};
        GFX_FX_OX = new int[]{18, 15, 10, 11, 28, 9, 11, 8, 26};
        GFX_FX_OY = new int[]{21, 21, 13, 10, 28, 9, 14, 8, 48};
        GFX_NUM_BOSS_SPRITES = new int[]{2, 4, 5, 4};
        GFX_BOSS_WIDTH = new int[][]{new int[]{58, 34}, new int[]{53, 63, 74, 65}, new int[]{44, 62, 49, 47, 25}, new int[]{57, 68, 61, 48}};
        GFX_BOSS_HEIGHT = new int[][]{new int[]{74, 33}, new int[]{62, 65, 71, 61}, new int[]{70, 80, 66, 62, 25}, new int[]{62, 72, 64, 39}};
        GFX_BOSS_OX = new int[][]{new int[]{29, 18}, new int[]{26, 31, 36, 34}, new int[]{22, 31, 26, 26, 12}, new int[]{28, 34, 29, 23}};
        GFX_BOSS_OY = new int[][]{new int[]{50, 19}, new int[]{48, 51, 55, 46}, new int[]{50, 60, 50, 50, 12}, new int[]{48, 55, 44, 20}};
        GFX_BOSS_DIRS = new int[][]{new int[]{1, 1}, new int[]{1, 1, 2, 1}, new int[]{1, 1, 1, 1}, new int[]{1, 1, 1, 1, 1}};
        GFX_BOSS_SHADOW = new boolean[]{true, true, false, false};
        GFX_BOSS_SHADOW_OY = new int[]{5, 11, 0, 0};
        GFX_JUMP_ZOMBIE2 = new int[]{0, 5, 6, 7, 8, 8, 8, 8, 7, 6, 5};
        GFX_JUMP_BURGER = new int[]{0, 0, 8, 12, 17, 17, 12, 8, 0, 0, 0};
        GFX_JUMP_BICLOPS = new int[]{0, 0, 9, 14, 17, 18};
        GFX_JUMP_BOUNCE = new int[]{0, 4, 5, 6, 6, 5, 4};
        GFX_JUMP_FLOAT = new int[]{3, 2, 2, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5, 5, 5, 5, 4, 4};
        GFX_JUMP_ARROW = 8;
        GFX_JUMP_MAGIC = 7;
        GFX_JUMP_EYE_FIRE = 16;
        GFX_JUMP_BUBBLE = 6;
        GFX_JUMP_FX = 6;
        GFX_JUMP_DROP = 16;
        GFX_JUMP_FALL = 128;
        GFX_JUMP_FOUND = 20;
        GFX_JUMP_PICKUP = 40;
        GFX_GRAVITY_DROP = 4;
        GFX_GRAVITY_FALL = 16;
        GFX_GRAVITY_FOUND = -2;
        DUNGEON_TILE = new int[0];
        DUNGEON_TRANSFORM = new int[0];
        OVERWORLD_TILE = new int[0];
        OVERWORLD_TRANSFORM = new int[0];
        GFX_SOFTKEY_WIDTH = 48;
        GFX_SOFTKEY_HEIGHT = 48;
        GFX_BORDER = 1;
        GFX_LOGO_WIDTH = 170;
        GFX_LOGO_HEIGHT = 70;
        GFX_BG_FINN_OX = 0;
        GFX_BG_FINN_OY = 0;
        GFX_TITLE_BORDER_WIDTH = 14;
        GFX_TITLE_BORDER_HEIGHT = 25;
        GFX_TITLE_BORDER_OX = 11;
        GFX_TITLE_BORDER_OY = 6;
        GFX_TITLE_BORDER_SIZE = 4;
        GFX_SCROLL_SIDE_WIDTH = 11;
        GFX_SCROLL_SIDE_HEIGHT = 38;
        GFX_SCROLL_END_WIDTH = 64;
        GFX_SCROLL_END_HEIGHT = 24;
        GFX_SCROLL_CENTER_WIDTH = 24;
        GFX_SCROLL_CENTER_HEIGHT = 24;
        GFX_SCROLL_END_OVER = 12;
        GFX_HAND_OX = -46;
        GFX_HAND_OY = 4;
        GFX_ARM_OY = 11;
        GFX_ARM_STRIPES = new int[]{1, 10, 2, 1};
        COLORS_ARM = new int[]{-2917084, -81356, -678360, -8109270};
        GFX_STATUS_ICON_WIDTH = 18;
        GFX_STATUS_ICON_HEIGHT = 18;
        GFX_STATUS_DIGIT_WIDTH = 10;
        GFX_STATUS_DIGIT_HEIGHT = 15;
        GFX_STATUS_DIGIT_WIDTHS = new int[]{10, 7, 9, 10, 10, 10, 10, 9, 10, 10};
        GFX_STATUS_ICON_SPACING = 4;
        GFX_STATUS_DIGITS_OY = 2;
        GFX_BRACKET_WIDTH = 30;
        GFX_BRACKET_HEIGHT = 30;
        GFX_BRACKET_OX = 3;
        GFX_BRACKET_OY = 3;
        GFX_PORTRAIT_WIDTH = 48;
        GFX_PORTRAIT_HEIGHT = 40;
        GFX_PORTRAIT_OVER = 6;
        GFX_MAP_GRID_WIDTH = 32;
        GFX_MAP_GRID_HEIGHT = 32;
        GFX_MAP_ROOM_INSET = 3;
        GFX_MAP_ROOM_WIDTH = GFX_MAP_GRID_WIDTH - (GFX_MAP_ROOM_INSET << 1);
        GFX_MAP_ROOM_HEIGHT = GFX_MAP_GRID_HEIGHT - (GFX_MAP_ROOM_INSET << 1);
        GFX_MAP_DOOR_WIDTH = 18;
        GFX_MAP_DOOR_OX = (GFX_MAP_GRID_WIDTH - GFX_MAP_DOOR_WIDTH) >> 1;
        GFX_MAP_DOOR_OY = (GFX_MAP_GRID_HEIGHT - GFX_MAP_DOOR_WIDTH) >> 1;
        GFX_MAP_ICON_WIDTH = 18;
        GFX_MAP_ICON_HEIGHT = 18;
        GFX_TOUCH_PAD_WIDTH = 164;
        GFX_TOUCH_PAD_HEIGHT = 164;
        GFX_TOUCH_DIR_WIDTH = 28;
        GFX_TOUCH_DIR_HEIGHT = 28;
        GFX_TOUCH_DIR_OX = new int[]{68, 68, 6, 130, 28, 107, 28, 108};
        GFX_TOUCH_DIR_OY = new int[]{8, 132, 70, 70, 30, 30, 109, 109};
        GFX_TOUCH_POS_OX = new int[]{68, 68, 6, 130, 6, 130, 6, 130};
        GFX_TOUCH_POS_OY = new int[]{8, 132, 70, 70, 8, 8, 132, 132};
        GFX_TOUCH_ACTION_WIDTH = 100;
        GFX_TOUCH_ACTION_HEIGHT = 100;
        GFX_TOUCHPAD_HBORDER = 8;
        GFX_TOUCHPAD_VBORDER = 16;
        GFX_TOUCH_CONTROLS_HSPACING = -16;
        GFX_TOUCH_CONTROLS_VSPACING = 0;
    }
}
